### ISSUE TITLE
[8.0.0] Issues for RN update

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#62]
### Description
List of issues that were not included in the release notes issued on 5.08.20, and they should.
We should update the RN.

The list is arranged in order: _title - a number with a link - description_ that can be helpful for the tech writer.

###  Fixed or not included, to be added to RN

1. * [x] Cannot read property 'defaultView' of undefined. [#6718](https://github.com/handsontable/handsontable/issues/6718) _Error when Handsontable is initialized with fixedRowsTop and fixedRowsBottom higher than rows length then the table throws errors while clicking the cells_. 
1. * [x] Using SPACE on non-contiguous checkbox-type cells [#4882](https://github.com/handsontable/handsontable/issues/4882)
_Using space  on non-contiguous checkbox-type cells is posibble_
1. * [x] Update to support Handsontable 8.0.0 version [#197](https://github.com/handsontable/angular-handsontable/issues/197) Angular-handsontable
1. * [x] Update to support v8.0.0 [#189](https://github.com/handsontable/react-handsontable/issues/189) React-Handsontable
1. * [x] Update to support v8.0.0 [#165](https://github.com/handsontable/vue-handsontable-official/issues/165) Vue-Handsontable
1. * [x] https://github.com/handsontable/handsontable/issues/6429
1. * [x] https://github.com/handsontable/handsontable/issues/4303
1. * [x] https://github.com/handsontable/handsontable/issues/6429
1. * [x] https://github.com/handsontable/handsontable/issues/4303
1. * [x] Inconsistency with context menu 'Remove columns' option [#6327](https://github.com/handsontable/dev-handsontable/issues/106)

### NOT fixed, to be removed from RN
1. * [x] https://github.com/handsontable/handsontable/issues/3914
1. * [x] https://github.com/handsontable/handsontable/issues/5889
1. * [x] https://github.com/handsontable/handsontable/issues/6874 - `regression from 8.0.0-beta2`
1. * [x] https://github.com/handsontable/handsontable/issues/3873

### Other confusing tasks to be corrected in RN
1. * [ ] **Fixed a problem where using filters and minSpareRows would make the table add an empty row at the beginning of the table. handsontable/handsontable#6278** incorrect URL
1. * [ ] **Fixed a problem, where using loadData after sorting would not work as expected. handsontable/handsontable#5956** incorrect URL
1. * [ ] https://github.com/handsontable/handsontable/issues/6204 wrong URL (2 times in the RN)
1. * [x] https://github.com/handsontable/handsontable/issues/6478 - fixed in 7.3.0 but also has the 8.0.0-beta2?
1. * [ ] handsontable/handsontable#5792 is mentioned two times in different places in the RN
1. * [ ] handsontable/handsontable#4999 is mentioned two times in different places in the RN
1. * [ ] handsontable/handsontable#4121 is mentioned two times in different places in the RN
1. * [ ] **Fixed an incorrect header name when user defined more columns in the nestedHeaders plugin. handsontable/handsontable#4716** doesn't seem to follow to the right issue. Other 4716 marked issue is next to it and it is OK.
1. * [ ] https://github.com/handsontable/handsontable/issues/4567 was added to RN but @wojciechczerniak wrote that it is a duplicate of handsontable/handsontable#5751
1. * [ ] https://github.com/handsontable/dev-handsontable/issues/130 is on the RN but does not have a Release attached to the issue and related to eco-renderers that are not finished

### Waiting for Clients confirmation (issue description not clear)
1. * [ ] Performance and CPU wastage issue due to some handsontable properties. [#6058](https://github.com/handsontable/handsontable/issues/6058)

**Comment by scarletfog** [comment]
The lack of consistency is present in both - the main repo and wrappers, you can compare:
https://github.com/handsontable/react-handsontable/releases/tag/3.1.3 - react wrapper
https://github.com/handsontable/handsontable/releases/tag/7.4.0 - hot

Some have issues, some have pulls assigned. We had a brief discussion with Chris about this "problem" and usually, we should aim at guiding the end-developer to the issue number. This also means restricting the issue to adequate points each PR should refer to(less messy as you pointed out). However, sometimes the PR has some interesting details in the description, or the issue is so broad that it has several PRs connected to it.

I hope it's clear for you, if you had something different in mind please let me know 😄
