### ISSUE TITLE
[DOCS] Add missing docs for testing tutorial

### ISSUE THREAD

**Issue by scarletfog** [handsontable/quality#88]
### Description

We miss the docs for `testing tutorial` in official documentation. We should describe how the following scripts work, and their effects:

- [ ] `test:e2e.dump`
- [ ] `test:mobile.dump`
- [ ] `test:production.dump`
- [ ] `test:walkontable.dump` 

Additional note:
Maybe worth adding to `README.md` || `CONTRIBUTING.md` || `package.json` as a comment
### Links
https://handsontable.com/docs/7.2.2/tutorial-testing.html

**Comment by aninde** [comment]
Issue moved to [handsontable/handsontable handsontable/dev-handsontable#344](https://github.com/handsontable/dev-handsontable/issues/344) via [**ZenHub**](https://www.zenhub.com/)
